version: "3"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: markapdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Asegúrate de que este nombre sea correcto
    image: backend:latest  # Asigna un nombre explícito a la imagen
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/markapdb}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
    ports:
      - "8080:8080"
    networks:
      - backend-network

  frontend:
    image: sebyex/markap:latest
    container_name: markap
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
