services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: markapdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  backend:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/markapdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
    ports:
      - "8080:8080"

  frontend:
    image: sebyex/markap:latest
    container_name: markap
    depends_on:
      - backend
    ports:
      - "3000:80"  # Mapea el puerto 80 del contenedor al puerto 3000 local